# Generated by Django 5.1.4 on 2024-12-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descrption',
            new_name='description',
        ),
    ]
